### PR TITLE
Fix NPE while extracting recoder error position and use existing information better

### PR DESCRIPTION
**Pull request by jwiesler**

### CODE REVIEW

**Review by WolframPfeifer — CHANGES_REQUESTED** [review]
Thanks for the quick fix!
However, could you please remove "var" from the code and make the types explicit? As far as I know, we agreed in a discussion that it makes the code more difficult to read. From my point of view, it is ok in tests and debug code, but not in the "core"/main classes.

**Comment by wadoon** [comment]
> Thanks for the quick fix! However, could you please remove "var" from the code and make the types explicit? As far as I know, we agreed in a discussion that it makes the code more difficult to read. From my point of view, it is ok in tests and debug code, but not in the "core"/main classes.

I am not aware that we agreed on a consens.

**Review by wadoon — APPROVED** [review]

**Comment by WolframPfeifer** [comment]
> > Thanks for the quick fix! However, could you please remove "var" from the code and make the types explicit? As far as I know, we agreed in a discussion that it makes the code more difficult to read. From my point of view, it is ok in tests and debug code, but not in the "core"/main classes.
> 
> I am not aware that we agreed on a consens.

I thought that we had, but maybe we should discuss it in our next meeting then...

**Comment by wadoon** [comment]
> I thought that we had, but maybe we should discuss it in our next meeting then...

For the discussion: For example, if the rhs is a constructor invocation, the type is clear. 

```java 
var x = new HashMap<Int, new HashMap<List<Int>, Function<String, String>>>;
```

**Comment by jwiesler** [comment]
@WolframPfeifer removed var where necessary.

**Comment by mattulbrich** [comment]
Julian @jwiesler, I added to this branch and created a PR in your repo.

**Comment by jwiesler** [comment]
@mattulbrich as a member you can just push to my branch in case you didn't know.

**Review by WolframPfeifer — APPROVED** [review]

**Pull request merged**
