### PR TITLE
Update issue templates

### PR DESCRIPTION
**Pull request by WolframPfeifer**
added templates for bug report and feature request

### CODE REVIEW

**Comment by mattulbrich** [comment]
Can we not essentially take the gitlab template?

In particular: stacktraces should be mentioned, reproducibility, and the commit SHA should be mandatory.
(And I prefer headings using `#` over `**`)

**Comment by wadoon** [comment]
Are the markdown templates the first step? And we will go for the formula solution in a second step?

**Comment by mattulbrich** [comment]
Yes, @wadoon, sounds good. I have copied the MDs from gitlab and adapted them to github. I'd be happy with that for the moment. Of course: Can be improved in a next iteration.

Can we undraft this, @WolframPfeifer ?

**Comment by WolframPfeifer** [comment]
My original plan was to use forms for this, but I do not have the time at the moment to prepare them sufficiently. So let's use the markdown templates for the moment.
Thanks, @mattulbrich!

Since I can not be reviewer (probably because I created the PR originally), @mi-ki will do the review.

**Review by mi-ki — APPROVED** [review]
Seems good to me, thanks for the effort!

**Pull request merged**
