### PR TITLE
JUnit XML files for RunAllProofs

### PR DESCRIPTION
**Pull request by wadoon**
This PR extends the RunAllProofs facility for the generation of JUnit files. Each test entry in `automaticJavaDL.txt` or `automaticInfflow.txt` results into an entry in a JUnit file. This allows later a processing of these tests in Jenkins/Gitlab and Co. 

Further changes are:
* Achieve a better catching of the stdout and stderr during the prove for inserting it into the JUnit files
* Upload the statistics as build artifacts

### CODE REVIEW

**Comment by jwiesler** [comment]
This MR added a file header to every .java file in the repo. Is this intended?

**Comment by wadoon** [comment]
> This MR added a file header to every .java file in the repo. Is this intended?

No. I think this occurred by using an old spotless configuration. 

This PR is still not ready.

**Comment by lks9** [comment]
Sorry, I don't see the proof results and I don't understand what this PR does exactly. So I cannot review this, unless it is a bit clearer to me.

**Comment by wadoon** [comment]
> Sorry, I don't see the proof results and I don't understand what this PR does exactly. So I cannot review this, unless it is a bit clearer to me.

Uploaded artifacts are a little bit hidden in Github, you can find them on the Github Action site:

https://github.com/KeYProject/key/actions/runs/4143092115

There is a download for `test-results` possible. 

In this archive you find the proof statistics:

image

and also 76 JUnit-XML files: 

image

The rest is code quality revision. 

A more beautiful presentation of the build artifacts is blocked (see #3010).

**Review by WolframPfeifer — APPROVED** [review]

**Pull request merged**
