### PR TITLE
Floating Point rules for casts

### PR DESCRIPTION
**Pull request by samysweb**
See (future) comment in #3023 that will mention this pull request in a few minutes

### CODE REVIEW

**Comment by wadoon** [comment]
@mattulbrich Has someone changed the branch protection settings? Github tells me I am able to merge this PR without an reviewer approval.

**Comment by samysweb** [comment]
@wadoon I believe this is probably the case because I only asked to merge this into KeYProject:mu/unbalancedFloats (and not into the protected main branch)

**Comment by jwiesler** [comment]
@wadoon tests aren't run either for this one.

**Comment by jwiesler** [comment]
And I thought this repo shouldn't be used for user branches ([mu/unbalancedFloats](https://github.com/KeYProject/key/tree/mu/unbalancedFloats), [weigl/java17](https://github.com/KeYProject/key/tree/weigl/java17))

**Comment by mattulbrich** [comment]
> @mattulbrich Has someone changed the branch protection settings? Github tells me I am able to merge this PR without an reviewer approval.

I have added you to the group of developers.

**Comment by samysweb** [comment]
@mattulbrich: If you're OK with that I will merge these changes into your `unbalancedFloats` branch.
This will run the entire test suite on this and tell us:
- If the additional `varcond` break any proofs (at least on my machine this didn't seem to be the case)
- Whether the changes significantly slow down the proofs due to the additional condition checks

**Pull request merged**
