### PR TITLE
Upload HTML test report

### PR DESCRIPTION
**Pull request by wadoon**
Changes to CI pipeline for uploading the HTML test report generated by Gradle.

In the second step these artifacts are gathered by https://github.com/KeYProject/artiweb/ to give more test insights. 

It also disables the failing (on external PR) test reporter action.

[Gradle Test Report from this branch](https://keyproject.github.io/artiweb/3010/535140696/key.core/build/reports/tests/testRunAllFunProofs/index.html).

### CODE REVIEW

**Comment by mattulbrich** [comment]
Sorry, I do not understand what this PR tries to achieve from the comments and descriptions here.

**Comment by wadoon** [comment]
> Sorry, I do not understand what this PR tries to achieve from the comments and descriptions here.

I changed the description.

**Comment by wadoon** [comment]
Artiweb, now with diagrams: https://keyproject.github.io/artiweb/3010/

https://keyproject.github.io/artiweb/3010/538902748/key.core.symbolic_execution/build/reports/tests/test/index.html

**Review by mattulbrich — APPROVED** [review]
After explanation, it became a bit clearer.

**Pull request merged**
